env: development
elasticsearch:
  url: http://localhost:9200
app:
  publicAPI: http://localhost:2997/api
picstitch: http://104.196.30.108:5000
nlp: http://104.196.51.184:8083
nlp_rnn: http://104.196.1.204:8085
